"""Markdown report generator for CI/CD and PR comments."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cloud_audit.models import ScanReport

_SEVERITY_MARKERS = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
    "info": "INFO",
}


def generate_markdown(report: ScanReport) -> str:
    """Generate a Markdown report string from a ScanReport."""
    from cloud_audit.models import Severity

    lines: list[str] = []
    s = report.summary

    # Header
    lines.append("# gcp-auditor scan report")
    lines.append("")
    lines.append(f"**Provider:** {report.provider.upper()}")
    lines.append(f"**Account:** {report.account_id or 'unknown'}")
    if report.regions:
        lines.append(f"**Regions:** {', '.join(report.regions)}")
    lines.append(f"**Duration:** {report.duration_seconds}s")
    lines.append(f"**Health Score:** {s.score}/100")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Resources scanned | {s.resources_scanned} |")
    lines.append(f"| Checks passed | {s.checks_passed} |")
    lines.append(f"| Checks failed | {s.checks_failed} |")
    if s.checks_errored:
        lines.append(f"| Checks errored | {s.checks_errored} |")
    lines.append(f"| Total findings | {s.total_findings} |")
    lines.append("")

    # Findings by severity
    if s.by_severity:
        lines.append("## Findings by severity")
        lines.append("")
        for sev in Severity:
            count = s.by_severity.get(sev, 0)
            if count:
                lines.append(f"- **{sev.value.upper()}:** {count}")
        lines.append("")

    # Findings table
    findings = report.all_findings
    if findings:
        severity_order = list(Severity)
        sorted_findings = sorted(findings, key=lambda f: severity_order.index(f.severity))

        lines.append("## Findings")
        lines.append("")
        lines.append("| Severity | Check | Region | Resource | Title |")
        lines.append("|----------|-------|--------|----------|-------|")

        for f in sorted_findings:
            marker = _SEVERITY_MARKERS.get(f.severity.value, f.severity.value)
            resource = f.resource_id[:40] + "..." if len(f.resource_id) > 40 else f.resource_id
            title = f.title[:60] + "..." if len(f.title) > 60 else f.title
            # Escape pipes in values to prevent breaking markdown table
            resource = resource.replace("|", "\\|")
            title = title.replace("|", "\\|")
            lines.append(f"| **{marker}** | {f.check_id} | {f.region} | `{resource}` | {title} |")

        lines.append("")
    else:
        lines.append("## Findings")
        lines.append("")
        lines.append("No issues found.")
        lines.append("")

    # Compliance references
    cis_refs = sorted({ref for f in findings for ref in f.compliance_refs if ref.startswith("CIS")})
    iso_refs = sorted({ref for f in findings for ref in f.compliance_refs if ref.startswith("ISO")})
    soc_refs = sorted({ref for f in findings for ref in f.compliance_refs if ref.startswith("SOC")})

    if cis_refs or iso_refs or soc_refs:
        lines.append("## Compliance coverage")
        lines.append("")

    if iso_refs:
        lines.append(f"**ISO 27001 Annex A:** {', '.join(iso_refs)}")
        lines.append("")

    if soc_refs:
        lines.append(f"**SOC 2 Trust Services Criteria:** {', '.join(soc_refs)}")
        lines.append("")

    if cis_refs:
        lines.append(f"**CIS GCP Benchmarks:** {', '.join(cis_refs)}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by [gcp-auditor](https://github.com/abdullahkamil/gcp-auditor)*")
    lines.append("")

    return "\n".join(lines)
